### ISSUE TITLE
Suggestion for fixing AppVeyors documentation page

### ISSUE THREAD

**Issue by r15ch13** [xt0rted/AppVeyor-Dark#11]
Hi, awesome style! Thank you 😄

The style works quite well on all pages of `appveyor.com`, not just `ci.appveyor.com`.
So I would like to suggest some small fixes for the documentation page.

## Fix for the sidebar and the footer:
```css
  .sidebar-content,
  .footer-container {
    background-color: #181818 !important;
    border-color: #343434 !important;
    color: #ccc !important;
  }
```
![image](https://user-images.githubusercontent.com/432127/64808004-afa2bf00-d596-11e9-8c2b-6937f304cb3a.png)

## Fix for the tables on [Windows images software](https://www.appveyor.com/docs/windows-images-software/):
```css
  table {
    background-color: #292929 !important;
  }
  table.software-list th.section {
    background-color: #181818 !important;
  }
  table tr:nth-of-type(2n) {
    background-color: #232323 !important;
  }
  th {
    background-color: #1f1f1f !important;
  }
  th,
  table tr td,
  table tr th {
    border-color: #343434 !important;
    color: #ccc !important;
  }
```
![image](https://user-images.githubusercontent.com/432127/64808100-e082f400-d596-11e9-8394-073e43c64cac.png)

## Fix edit invitation:
```css
  .edit-page-invitation {
    background-color: #181818 !important;
  }
```
![image](https://user-images.githubusercontent.com/432127/64807703-0fe53100-d596-11e9-8062-385162d87074.png)
