### ISSUE TITLE
broken styled error page

### ISSUE THREAD

**Issue by the-j0k3r** [xt0rted/AppVeyor-Dark#5]
An example `https://ci.appveyor.com/api/buildjobs/tcjixorwlxu6b2rs/artifacts/*` (must have last * in link)

styled looks quite bad and some text is unreadable.

@xt0rted Ill play around with css and see if I can find some fix. No promises

**Comment by the-j0k3r** [comment]
fix for this is 

```css
    pre {
        background-color:#ffc !important;
        border-color: #ffff7e !important;
        color: #000 !important;
    }
```

instead of whats there now.

I also found another bug in https://ci.appveyor.com/tools/encrypt
