### ISSUE TITLE
fix encrypt page code boxes

### ISSUE THREAD

**Issue by the-j0k3r** [xt0rted/AppVeyor-Dark#6]
![capture](https://user-images.githubusercontent.com/31389848/39142429-921e658c-4722-11e8-8b4a-59e627fc6504.PNG)

the fix is this

```css
    code {
        background-color: rgba(16, 33, 50, .64) !important;
        border: 1px solid rgb(46, 96, 145) !important;
        color: #9daccc !important;
    }
```

makes it look like GithubDark topi/label boxes which is nice.

@xt0rted need to merge https://github.com/xt0rted/AppVeyor-Dark/pull/4 before I can make more pull requests since my fixes are on top of those changes.
